<?php

namespace DoctrineProxies\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NmtApplicationUom extends \Application\Entity\NmtApplicationUom implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'uomCode', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'uomName', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'uomDescription', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'conversionFactor', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'sector', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'symbol', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'createdOn', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'createdBy', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'company'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'uomCode', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'uomName', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'uomDescription', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'conversionFactor', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'sector', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'symbol', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'createdOn', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'createdBy', '' . "\0" . 'Application\\Entity\\NmtApplicationUom' . "\0" . 'company'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NmtApplicationUom $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUomCode($uomCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUomCode', [$uomCode]);

        return parent::setUomCode($uomCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getUomCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUomCode', []);

        return parent::getUomCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setUomName($uomName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUomName', [$uomName]);

        return parent::setUomName($uomName);
    }

    /**
     * {@inheritDoc}
     */
    public function getUomName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUomName', []);

        return parent::getUomName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUomDescription($uomDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUomDescription', [$uomDescription]);

        return parent::setUomDescription($uomDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getUomDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUomDescription', []);

        return parent::getUomDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setConversionFactor($conversionFactor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConversionFactor', [$conversionFactor]);

        return parent::setConversionFactor($conversionFactor);
    }

    /**
     * {@inheritDoc}
     */
    public function getConversionFactor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConversionFactor', []);

        return parent::getConversionFactor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSector($sector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', [$sector]);

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', []);

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function setSymbol($symbol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSymbol', [$symbol]);

        return parent::setSymbol($symbol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSymbol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSymbol', []);

        return parent::getSymbol();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\Application\Entity\MlaUsers $createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(\Application\Entity\NmtApplicationCompany $company = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

}
